version: '2'
services:
  postgres:
    build: ./Docker/postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234qwer
      - POSTGRES_HOST=postgres
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      dockerfile: ./Docker/backend/Dockerfile
      context: .
    links:
      - postgres
      - rabbit
      - redis
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app
    command: ./run_web.sh
    security_opt:
        - label:disable
    ports:
      - "8000:8000"
      - "5555:5555"
    restart: always
 
  worker:
    build:
      dockerfile: ./Docker/backend/Dockerfile
      context: .
    links:
      - postgres
      - rabbit
      - redis
    depends_on:
      - rabbit
    volumes:
      - ./:/usr/src/app
    command: ./run_celery.sh
    security_opt:
      - label:disable
    restart: always

  rabbit:
    image: rabbitmq:3.6.14
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:3.2.11

  nginx:
    build: 
      dockerfile: ./Docker/nginx/Dockerfile
      context: .
    volumes:
      - ./Docker/nginx/config.dev:/etc/nginx/conf.d/default.conf
    security_opt:
      - label:disable
    ports:
      - "8080:80"
    depends_on:
      - backend
volumes:
  pgdata:
